name: Docker build
on: 
  push:
    branches:
      - main

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP CLI build  
        uses: aevea/action-kaniko@master
        with:
          path: cli/
          image: digital-entropy/dokar-php/cli
          tag: "8.0"

  build-fpm:
    needs: build-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP FPM build  
        uses: aevea/action-kaniko@master
        with:
          path: fpm/
          image: digital-entropy/dokar-php/fpm
          tag: "8.0"

  build-nginx:
    needs: build-fpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP NGINX build  
        uses: aevea/action-kaniko@master
        with:
          path: nginx/
          image: digital-entropy/dokar-php/nginx
          tag: "8.0"
